// Generated by CoffeeScript 1.10.0
var con, inputEl, ipc, nconsole;

ipc = require('electron').ipcRenderer;

con = require('console');

nconsole = new con.Console(process.stdout, process.stderr);

inputEl = document.getElementById('search-input');

nconsole.log("IN SEARCH VIEW");

nconsole.log(inputEl);

inputEl.addEventListener('input', function() {
  if (inputEl.value.length === 0) {
    nconsole.log("STOP SEARCH " + inputEl.value);
    ipc.send('stop-search');
    inputEl.focus();
    return;
  }
  ipc.send('perform-search', inputEl.value);
  nconsole.log("PERFORM SEARCH " + inputEl.value);
  return inputEl.focus();
});

ipc.on('found-in-page', function(event, result) {
  nconsole.log("IN SEARCH: found in page " + result.activeMatchOrdinal + "/" + result.matches);
});
