// Generated by CoffeeScript 1.10.0
var cancelEl, inputEl, ipc, nextEl, prevEl;

ipc = require('electron').ipcRenderer;

inputEl = document.getElementById('search-input');

prevEl = document.getElementById('search-prev');

nextEl = document.getElementById('search-next');

cancelEl = document.getElementById('search-cancel');

nextEl.addEventListener('click', function() {
  if (!nextEl.disabled && inputEl.value.length > 0) {
    ipc.send('search-next', inputEl.value);
    return inputEl.focus();
  }
});

prevEl.addEventListener('click', function() {
  if (!prevEl.disabled && inputEl.value.length > 0) {
    ipc.send('search-prev', inputEl.value);
    return inputEl.focus();
  }
});

cancelEl.addEventListener('click', function() {
  ipc.send('stop-search', inputEl.value);
  return console.log("stop-search");
});

inputEl.addEventListener('input', function() {
  if (inputEl.value.length === 0) {
    prevEl.disabled = true;
    nextEl.disabled = true;
    ipc.send('clear-search');
    inputEl.focus();
    return;
  }
  prevEl.disabled = false;
  nextEl.disabled = false;
  ipc.send('perform-search', inputEl.value);
  console.log("PERFORM SEARCH " + inputEl.value);
  return inputEl.focus();
});

ipc.on('get-focus', function() {
  console.log('got focus');
  inputEl.focus();
});

ipc.on('found-in-page', function(event, result) {
  console.log("IN SEARCH: found in page " + result.activeMatchOrdinal + "/" + result.matches);
});
